#include <algorithm>
#include <shaders.h>
#include <volume3dview.h>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>

Volume3dView::Volume3dView(Camera* c) : cam(c)
{
}

Volume3dView::~Volume3dView()
{
    glDeleteBuffers(1, &vertex_buffer);
    glDeleteVertexArrays(1, &vertex_array_id);
    glDisableVertexAttribArray(aPos_attribute);
    glDisableVertexAttribArray(aTexCoord_attribute);
    delete shaderProgram;
}

//these volumes generated by AI procedures
void fillCylinder(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float radius = width * 0.3f; // 30% of width

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                if ((dx * dx + dy * dy) <= (radius * radius)) {
                    volumeData[x + y * width + z * width * height] = 255;
                }
            }
        }
    }
}

void fillCylinder2(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float radius = width * 0.3f; // 30% of width

    for (int z = 0; z < depth; ++z) {
        float zFactor = static_cast<float>(z) / static_cast<float>(depth - 1); // range [0,1]

        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                float dist = std::sqrt(dx * dx + dy * dy);

                if (dist <= radius) {
                    // Varying intensity using radial and depth-based modulation
                    float radialFactor = std::cos((dist / radius) * 3.1415f); // range [-1,1]
                    float intensity = (radialFactor * 0.5f + 0.5f) * zFactor;  // range [0,1]
                    GLubyte value = static_cast<GLubyte>(std::clamp(intensity * 255.0f, 0.0f, 255.0f));

                    int index = x + y * width + z * width * height;
                    volumeData[index] = value;
                }
                else {
                    // Outside the cylinder
                    int index = x + y * width + z * width * height;
                    volumeData[index] = 0;
                }
            }
        }
    }
}

void fillHollowCylinder(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float outerRadius = width * 0.3f;       // 30% of width
    float innerRadius = outerRadius * 0.5f; // 50% of outer radius

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                float dist = std::sqrt(dx * dx + dy * dy);

                int index = x + y * width + z * width * height;

                if (dist >= innerRadius && dist <= outerRadius) {
                    float radialFactor = std::cos((dist - innerRadius) / (outerRadius - innerRadius) * 3.1415f);
                    float intensity = (radialFactor * 0.5f + 0.5f); // Z-agnostic
                    volumeData[index] = static_cast<GLubyte>(std::clamp(intensity * 255.0f, 0.0f, 255.0f));
                }
                else {
                    volumeData[index] = 0;
                }
            }
        }
    }
}



void fillSphere(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float cz = depth / 2.0f;
    float radius = 20.0f;

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                float dz = z - cz;
                float dist2 = dx * dx + dy * dy + dz * dz;
                if (dist2 < radius * radius) {
                    volumeData[x + y * width + z * width * height] = 255;
                }
                else {
                    volumeData[x + y * width + z * width * height] = 0;
                }
            }
        }
    }
}

void fillTorus(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float cz = depth / 2.0f;

    float R = 200.0f;  // major radius
    float r = 50.0f;   // minor radius

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                float dz = z - cz;

                float xyLen = sqrt(dx * dx + dy * dy);
                float dist = (xyLen - R) * (xyLen - R) + dz * dz;

                if (dist < r * r) {
                    volumeData[x + y * width + z * width * height] = 255;
                }
            }
        }
    }
}

void fillKleinBottle(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    int w = width, h = height, d = depth;
    auto idx = [&](int x, int y, int z) {
        return x + y * w + z * w * h;
        };

    const float pi = 3.14159265f;

    for (float u = 0; u < 2.0f * pi; u += 0.015f) {
        for (float v = 0; v < 2.0f * pi; v += 0.015f) {
            float r = 2.0f;

            float x = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * cos(u);
            float y = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * sin(u);
            float z = sin(u / 2.0f) * sin(v) + cos(u / 2.0f) * sin(2.0f * v);

            // Scale and center in volume
            int xi = static_cast<int>((x * 50.0f) + w / 2);
            int yi = static_cast<int>((y * 50.0f) + h / 2);
            int zi = static_cast<int>((z * 50.0f) + d / 2);

            for (int dz = -1; dz <= 1; ++dz)
                for (int dy = -1; dy <= 1; ++dy)
                    for (int dx = -1; dx <= 1; ++dx) {
                        int nx = xi + dx, ny = yi + dy, nz = zi + dz;
                        if (nx >= 0 && ny >= 0 && nz >= 0 && nx < w && ny < h && nz < d)
                            volumeData[idx(nx, ny, nz)] = 255;
                    }
        }
    }
}

void fillKleinBottle2(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    int w = width, h = height, d = depth;
    auto idx = [&](int x, int y, int z) {
        return x + y * w + z * w * h;
        };

    for (float u = 0; u < 2.0f * 3.14159f; u += 0.02f) {
        for (float v = 0; v < 2.0f * 3.14159f; v += 0.02f) {
            float r = 4.0f * (1 - cos(u) / 2.0f);

            float x = (6.0f * cos(u) * (1 + sin(u))) + r * cos(v);
            float y = (16.0f * sin(u)) + r * sin(v);
            float z = -2.0f * sin(u);

            // Center and scale into volume
            int xi = static_cast<int>(x * 10 + w / 2);
            int yi = static_cast<int>(y * 10 + h / 2);
            int zi = static_cast<int>(z * 10 + d / 2);

            // Draw a small sphere around each point
            for (int dz = -1; dz <= 1; ++dz)
                for (int dy = -1; dy <= 1; ++dy)
                    for (int dx = -1; dx <= 1; ++dx) {
                        int nx = xi + dx, ny = yi + dy, nz = zi + dz;
                        if (nx >= 0 && ny >= 0 && nz >= 0 && nx < w && ny < h && nz < d)
                            volumeData[idx(nx, ny, nz)] = 255;
                    }
        }
    }
}

void fillKleinBottleFigure8(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    int w = width, h = height, d = depth;
    auto idx = [&](int x, int y, int z) {
        return x + y * w + z * w * h;
        };

    for (float u = 0; u < 2.0f * 3.14159f; u += 0.02f) {
        for (float v = 0; v < 2.0f * 3.14159f; v += 0.02f) {
            float r = 2.0f;

            float x = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * cos(u);
            float y = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * sin(u);
            float z = sin(u / 2.0f) * sin(v) + cos(u / 2.0f) * sin(2.0f * v);

            // Apply figure-8 warping
            x += 0.5f * cos(2 * u);
            y += 0.5f * sin(3 * v);
            z += 0.3f * cos(u + v);

            int xi = static_cast<int>(x * 10 + w / 2);
            int yi = static_cast<int>(y * 10 + h / 2);
            int zi = static_cast<int>(z * 10 + d / 2);

            for (int dz = -1; dz <= 1; ++dz)
                for (int dy = -1; dy <= 1; ++dy)
                    for (int dx = -1; dx <= 1; ++dx) {
                        int nx = xi + dx, ny = yi + dy, nz = zi + dz;
                        if (nx >= 0 && ny >= 0 && nz >= 0 && nx < w && ny < h && nz < d)
                            volumeData[idx(nx, ny, nz)] = 255;
                    }
        }
    }
}

void fillKleinBottleSwirl(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    int w = width, h = height, d = depth;
    auto idx = [&](int x, int y, int z) {
        return x + y * w + z * w * h;
        };

    for (float u = 0; u < 2.0f * 3.14159f; u += 0.015f) {
        for (float v = 0; v < 2.0f * 3.14159f; v += 0.015f) {
            // Radius changes with sin(3u) for swirl effect
            float r = 4.0f + 2.0f * sin(3.0f * u);

            float x = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * cos(u);
            float y = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * sin(u);
            float z = sin(u / 2.0f) * sin(v) + cos(u / 2.0f) * sin(2.0f * v);

            int xi = static_cast<int>(x * 7 + w / 2);
            int yi = static_cast<int>(y * 7 + h / 2);
            int zi = static_cast<int>(z * 7 + d / 2);

            for (int dz = -1; dz <= 1; ++dz)
                for (int dy = -1; dy <= 1; ++dy)
                    for (int dx = -1; dx <= 1; ++dx) {
                        int nx = xi + dx, ny = yi + dy, nz = zi + dz;
                        if (nx >= 0 && ny >= 0 && nz >= 0 && nx < w && ny < h && nz < d)
                            volumeData[idx(nx, ny, nz)] = 255;
                    }
        }
    }
}

void fillMengerSponge(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    auto isHole = [](int x, int y, int z) {
        x = (x / 64) % 3;
        y = (y / 64) % 3;
        z = (z / 64) % 3;
        return (x == 1 && y == 1) || (y == 1 && z == 1) || (x == 1 && z == 1);
        };

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                if (!isHole(x, y, z))
                    volumeData[x + y * width + z * width * height] = 255;
            }
        }
    }
}

void fillTwistedTube(std::vector<GLubyte>& volumeData, int width, int height, int depth)
{
    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float fx = (x - width / 2.0f);
                float fy = (y - height / 2.0f);
                float fz = (z - depth / 2.0f);

                float angle = fz * 0.02f;
                float tx = fx * cos(angle) - fy * sin(angle);
                float ty = fx * sin(angle) + fy * cos(angle);

                float r = sqrt(tx * tx + ty * ty);
                if (r < 60.0f)
                    volumeData[x + y * width + z * width * height] = 255;
            }
        }
    }
}

void fillKleinBottlePinched(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    int w = width, h = height, d = depth;
    auto idx = [&](int x, int y, int z) {
        return x + y * w + z * w * h;
        };

    for (float u = 0; u < 2.0f * 3.14159f; u += 0.015f) {
        for (float v = 0; v < 2.0f * 3.14159f; v += 0.015f) {
            float r = 6.0f + 3.0f * sin(2.0f * v) * sin(3.0f * u);

            float x = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * cos(u);
            float y = (r + cos(u / 2.0f) * sin(v) - sin(u / 2.0f) * sin(2.0f * v)) * sin(u);
            float z = sin(u / 2.0f) * sin(v) + cos(u / 2.0f) * sin(2.0f * v);

            int xi = static_cast<int>(x * 6 + w / 2);
            int yi = static_cast<int>(y * 6 + h / 2);
            int zi = static_cast<int>(z * 6 + d / 2);

            for (int dz = -1; dz <= 1; ++dz)
                for (int dy = -1; dy <= 1; ++dy)
                    for (int dx = -1; dx <= 1; ++dx) {
                        int nx = xi + dx, ny = yi + dy, nz = zi + dz;
                        if (nx >= 0 && ny >= 0 && nz >= 0 && nx < w && ny < h && nz < d)
                            volumeData[idx(nx, ny, nz)] = 255;
                    }
        }
    }
}

void fillCup(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float outerRadius = width * 0.3f;       // Outer wall
    float innerRadius = outerRadius * 0.6f; // Hollow center
    int baseHeight = depth * 0.2f;          // Base thickness in slices

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                float dist = std::sqrt(dx * dx + dy * dy);
                int index = x + y * width + z * width * height;

                // Bottom base of the cup
                if (z < baseHeight && dist <= outerRadius) {
                    volumeData[index] = 255;
                }
                // Side walls of the cup (hollow interior)
                else if (z >= baseHeight && dist >= innerRadius && dist <= outerRadius) {
                    volumeData[index] = 255;
                }
                else {
                    volumeData[index] = 0;
                }
            }
        }
    }
}

void fillCupWithHandle(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    float cx = width / 2.0f;
    float cy = height / 2.0f;
    float outerRadius = width * 0.3f;
    float innerRadius = outerRadius * 0.6f;
    int baseHeight = depth * 0.2f;

    // Cup body
    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - cx;
                float dy = y - cy;
                float dist = std::sqrt(dx * dx + dy * dy);
                int index = x + y * width + z * width * height;

                if ((z < baseHeight && dist <= outerRadius) ||
                    (z >= baseHeight && dist >= innerRadius && dist <= outerRadius)) {
                    volumeData[index] = 255;
                }
            }
        }
    }

    // Handle as a torus segment
    float handleRadius = outerRadius * 0.6f;       // Radius of the donut
    float handleTube = outerRadius * 0.15f;        // Thickness of the handle tube
    float hx = cx + outerRadius + handleTube * 1.5f; // Center of the torus, X side of cup
    float hy = cy;                                  // Align vertically with cup center
    float hz = depth * 0.5f;                        // Center height of the handle

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                float dx = x - hx;
                float dy = y - hy;
                float dz = z - hz;
                float dxy = std::sqrt(dy * dy + dz * dz);
                float torusDist = std::sqrt((dxy - handleRadius) * (dxy - handleRadius) + dx * dx);

                int index = x + y * width + z * width * height;
                if (torusDist <= handleTube)
                    volumeData[index] = 255;
            }
        }
    }
}

void fillCupWithHandle2(std::vector<GLubyte>& volumeData, int width, int height, int depth) {
    float cx = width / 2.0f;
    float cy = height * 0.3f;
    float cz = depth / 2.0f;

    float cupHeight = height * 0.6f;
    float outerRadius = width * 0.25f;
    float innerRadius = outerRadius * 0.7f;
    float wallThickness = outerRadius - innerRadius;

    // Handle scaled down by 75%
    float handleRadius = cupHeight * 0.4f * 0.75f;
    float handleThickness = wallThickness * 0.75f;
    float handleCenterX = cx + outerRadius + handleThickness * 1.5f;
    float handleCenterY = cy + cupHeight * 0.5f;

    float baseThickness = wallThickness * 0.10f;  // base half as thick

    for (int z = 0; z < depth; ++z) {
        for (int y = 0; y < height; ++y) {
            for (int x = 0; x < width; ++x) {
                int idx = x + y * width + z * width * height;

                float dx = x - cx;
                float dy = y - cy;
                float dz = z - cz;

                // Cup body
                float radialDist = std::sqrt(dx * dx + dz * dz);
                bool inCupWall = dy >= 0 && dy <= cupHeight &&
                    radialDist >= innerRadius && radialDist <= outerRadius;

                bool inBase = dy < baseThickness && radialDist <= outerRadius;

                // Handle in XY plane, 75% smaller
                float hx = x - handleCenterX;
                float hy = y - handleCenterY;
                float hz = z - cz;
                float handleCircleDist = std::sqrt(hx * hx + hy * hy);
                bool inHandle = std::abs(hz) < handleThickness &&
                    handleCircleDist >= handleRadius - handleThickness &&
                    handleCircleDist <= handleRadius + handleThickness;

                volumeData[idx] = (inCupWall || inBase || inHandle) ? 255 : 0;
            }
        }
    }
}

void Volume3dView::Setup(Context* ctx)
{
    context = ctx;

    Setup();
}

void Volume3dView::Setup()
{
    initializeOpenGLFunctions();

    std::string vertexShaderSource = readSourceFile(".\\shaders\\volume3dview.vert");
    std::string fragmentShaderSource = readSourceFile(".\\shaders\\volume3dview.frag");

    shaderProgram = new QOpenGLShaderProgram();
    bool success = shaderProgram->addShaderFromSourceCode(QOpenGLShader::Vertex, vertexShaderSource.c_str());
    success = shaderProgram->addShaderFromSourceCode(QOpenGLShader::Fragment, fragmentShaderSource.c_str());
    success = shaderProgram->link();

    // === 1. Generate Dummy Volume Data ===
    //const int width = 256; 
    //const int height = 256;
    //const int depth = 256; 

    const int width = context->volumeData.getHeader()->recoX;
    const int height = context->volumeData.getHeader()->recoY;
    const int depth = context->volumeData.getHeader()->recoZ;

    //fillCupWithHandle2(volumeDataTex, width, height, depth);
    //fillHollowCylinder(volumeDataTex, width, height, depth);
   
    // === 2. Create 3D Texture ===

    glGenTextures(1, &tex3D);
    glBindTexture(GL_TEXTURE_3D, tex3D);
    glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
    glTexImage3D(GL_TEXTURE_3D, 0, GL_R8, width, height, depth, 0,
        GL_RED, GL_UNSIGNED_BYTE, context->volumeData.getVolumeDataTex().data());

    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);

    // === 3. Create Cube Geometry ===
    float cube[] = {
        // pos              // texcoord
        //-1,-1,-1,  0,0,0,
        // 1,-1,-1,  1,0,0,
        // 1, 1,-1,  1,1,0,
        //-1, 1,-1,  0,1,0,
        //-1,-1, 1,  0,0,1,
        // 1,-1, 1,  1,0,1,
        // 1, 1, 1,  1,1,1,
        //-1, 1, 1,  0,1,1,

        // Each face of the cube as triangles (12 triangles, 36 vertices total)
        // Back face
        -1,-1,-1,0,0,0,  1, 1,-1,1,1,0,  1,-1,-1,1,0,0,
        -1,-1,-1,0,0,0, -1, 1,-1,0,1,0,  1, 1,-1,1,1,0,
        // Front face
        -1,-1, 1,0,0,1,  1,-1, 1,1,0,1,  1, 1, 1,1,1,1,
        -1,-1, 1,0,0,1,  1, 1, 1,1,1,1, -1, 1, 1,0,1,1,
        // Left face
        -1,-1,-1,0,0,0, -1,-1, 1,0,0,1, -1, 1, 1,0,1,1,
        -1,-1,-1,0,0,0, -1, 1, 1,0,1,1, -1, 1,-1,0,1,0,
        // Right face
         1,-1,-1,1,0,0,  1, 1,-1,1,1,0,  1, 1, 1,1,1,1,
         1,-1,-1,1,0,0,  1, 1, 1,1,1,1,  1,-1, 1,1,0,1,
         // Bottom face
         -1,-1,-1,0,0,0,  1,-1,-1,1,0,0,  1,-1, 1,1,0,1,
         -1,-1,-1,0,0,0,  1,-1, 1,1,0,1, -1,-1, 1,0,0,1,
         // Top face
         -1, 1,-1,0,1,0, -1, 1, 1,0,1,1,  1, 1, 1,1,1,1,
         -1, 1,-1,0,1,0,  1, 1, 1,1,1,1,  1, 1,-1,1,1,0
    };

    int dims[3] = { width, height, depth };

    int maxDimElement = *std::max_element(dims, dims + 3);
    size_t dispSize = 50;

    for (int ii = 0; ii < 36; ++ii) 
    {
        cube[ii * 6 + 0] *= (dispSize * width / maxDimElement);   // x
        cube[ii * 6 + 1] *= (dispSize * height / maxDimElement);  // y
        cube[ii * 6 + 2] *= (dispSize * depth / maxDimElement);   // z
    }

    cubeWorldVec = { dispSize * width / maxDimElement,
                        dispSize* height / maxDimElement,
                        dispSize* depth / maxDimElement };

    glGenVertexArrays(1, &vertex_array_id);
    glBindVertexArray(vertex_array_id);

    glGenBuffers(1, &vertex_buffer);
    glBindBuffer(GL_ARRAY_BUFFER, vertex_buffer);
    glBufferData(GL_ARRAY_BUFFER, sizeof(cube), cube, GL_STATIC_DRAW);

    aPos_attribute = glGetAttribLocation(shaderProgram->programId(), "aPos");
    glVertexAttribPointer(aPos_attribute, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(aPos_attribute);

    aTexCoord_attribute = glGetAttribLocation(shaderProgram->programId(), "aTexCoord");
    glVertexAttribPointer(aTexCoord_attribute, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(float), (void*)(3 * sizeof(float)));
    glEnableVertexAttribArray(aTexCoord_attribute);

    model_view = glGetUniformLocation(shaderProgram->programId(), "model_view");
    projection = glGetUniformLocation(shaderProgram->programId(), "projection");
    invModelViewProj = glGetUniformLocation(shaderProgram->programId(), "invMVP");
    cameraPos = glGetUniformLocation(shaderProgram->programId(), "cameraPos");
    windowWidth = glGetUniformLocation(shaderProgram->programId(), "windowWidth");
    windowHeight = glGetUniformLocation(shaderProgram->programId(), "windowHeight");
    minVal = glGetUniformLocation(shaderProgram->programId(), "minVal");
    maxVal = glGetUniformLocation(shaderProgram->programId(), "maxVal");
    cubeWorld = glGetUniformLocation(shaderProgram->programId(), "cubeWorld");

    model_matrix = glm::mat4(1.0f);
}

void Volume3dView::UpdateModel(const glm::mat4& cam_view, int winWidth, int winHeight, float minVoxelThreshold, float maxVoxelThreshold)
{
    UpdateModel(cam_view);

    windowWidthValue = winWidth;
    windowHeightValue = winHeight;
    minVoxelThresholdValue = minVoxelThreshold;
    maxVoxelThresholdValue = maxVoxelThreshold;
}

void Volume3dView::UpdateModel(const glm::mat4& cam_view)
{
    SetPosition(0, 0, 0);

    auto mm = glm::translate(model_matrix, glm::vec3(_X, _Y, _Z));
    model_view_matrix = cam_view * mm;
}

void Volume3dView::SetProjection(glm::mat4 p)
{
    projection_matrix = p;
}

void Volume3dView::Draw()
{
    shaderProgram->bind();

    glUniformMatrix4fv(model_view, 1, GL_FALSE, glm::value_ptr(model_view_matrix));
    glUniformMatrix4fv(projection, 1, GL_FALSE, glm::value_ptr(projection_matrix));

    glm::mat4 mvp = projection_matrix * model_view_matrix;
    glm::mat4 invMVP = glm::inverse(mvp);

    glUniformMatrix4fv(invModelViewProj, 1, GL_FALSE, glm::value_ptr(invMVP));

    glm::vec3 camPosition = cam->getPosition();
    glUniform3fv(cameraPos, 1, glm::value_ptr(camPosition));

    glUniform1i(windowWidth, windowWidthValue);
    glUniform1i(windowHeight, windowHeightValue);

    glUniform1f(minVal, minVoxelThresholdValue);
    glUniform1f(maxVal, maxVoxelThresholdValue);

    glUniform3fv(cubeWorld, 1, glm::value_ptr(cubeWorldVec));

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_3D, tex3D);
    GLuint te = glGetUniformLocation(shaderProgram->programId(), "volumeTex");
    glUniform1i(te, 0);

    glBindVertexArray(vertex_array_id);
    glDrawArrays(GL_TRIANGLES, 0, 36);  // full cube

    shaderProgram->release();
}
